import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type Database from 'better-sqlite3';
import { SessionStore } from '../db/sessions.js';
import { KnowledgeStore } from '../db/knowledge.js';
import { detectProject } from '../ingest/project-detector.js';
import { getAgentMemoryDir } from './exporter.js';
import type { Session } from '../types.js';

/** Generate HANDOFF.md from the most recent sessions */
export function generateHandoff(db: Database.Database, projectPath: string, sessions?: Session[]): string {
  const project = detectProject(projectPath);
  const sessionStore = new SessionStore(db);
  const knowledgeStore = new KnowledgeStore(db);

  const recentSessions = sessions ?? sessionStore.getRecent(project.id, 5);
  const knowledge = knowledgeStore.getByProject(project.id);
  const latest = recentSessions[0];

  const lines: string[] = [];
  lines.push('# Agent Handoff');
  lines.push('');
  lines.push(`> Auto-generated by [cross-agent-memory](https://github.com/stefanvo78/cross-agent-memory). Do not edit manually.`);
  lines.push('');
  lines.push(`**Project:** ${project.name} (${project.id})`);
  lines.push(`**Last updated:** ${new Date().toISOString()}`);
  lines.push(`**Sessions tracked:** ${recentSessions.length}`);
  lines.push('');

  if (latest) {
    lines.push('## Latest Session');
    lines.push('');
    lines.push(`- **Agent:** ${latest.agent}`);
    lines.push(`- **When:** ${latest.endedAt}`);
    lines.push(`- **Summary:** ${latest.summary}`);
    lines.push('');

    if (latest.tasksPending.length > 0) {
      lines.push('### Pending Tasks');
      lines.push('');
      for (const task of latest.tasksPending) {
        lines.push(`- [ ] ${task}`);
      }
      lines.push('');
    }

    if (latest.filesModified.length > 0) {
      lines.push('### Files Modified');
      lines.push('');
      for (const file of latest.filesModified) {
        lines.push(`- \`${file}\``);
      }
      lines.push('');
    }

    if (latest.keyDecisions.length > 0) {
      lines.push('### Key Decisions');
      lines.push('');
      for (const decision of latest.keyDecisions) {
        lines.push(`- ${decision}`);
      }
      lines.push('');
    }
  }

  if (recentSessions.length > 1) {
    lines.push('## Session History');
    lines.push('');
    lines.push('| Agent | When | Summary |');
    lines.push('|-------|------|---------|');
    for (const s of recentSessions) {
      const shortSummary = s.summary.length > 80 ? s.summary.slice(0, 80) + '...' : s.summary;
      lines.push(`| ${s.agent} | ${s.endedAt} | ${shortSummary} |`);
    }
    lines.push('');
  }

  if (knowledge.length > 0) {
    lines.push('## Shared Knowledge');
    lines.push('');
    for (const k of knowledge) {
      lines.push(`### ${k.title}`);
      lines.push(`*${k.type}* — ${k.content}`);
      lines.push('');
    }
  }

  const content = lines.join('\n');
  const dir = getAgentMemoryDir(projectPath);
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, 'HANDOFF.md'), content);
  return content;
}
