import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtempSync, readFileSync, existsSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import type Database from 'better-sqlite3';
import { createTestDb } from '../../src/db/connection.js';
import { SessionStore } from '../../src/db/sessions.js';
import { KnowledgeStore } from '../../src/db/knowledge.js';
import { generateHandoff } from '../../src/sync/handoff.js';
import type { SessionData } from '../../src/types.js';

function makeSession(overrides: Partial<SessionData> = {}): SessionData {
  return {
    id: 'sess-h1',
    agent: 'copilot',
    projectId: 'local/test-project',
    projectPath: '/tmp/test-project',
    endedAt: '2025-01-15T10:00:00',
    summary: 'Implemented authentication module with JWT support',
    tasksCompleted: ['Add JWT auth', 'Write tests'],
    tasksPending: ['Add refresh tokens', 'Add rate limiting'],
    filesModified: ['src/auth.ts', 'src/middleware.ts'],
    keyDecisions: ['Use bcrypt for hashing', 'JWT expiry 1 hour'],
    ...overrides,
  };
}

describe('Handoff Generator', () => {
  let db: Database.Database;
  let tmpDir: string;

  beforeEach(() => {
    db = createTestDb();
    tmpDir = mkdtempSync(join(tmpdir(), 'cam-handoff-'));
  });

  afterEach(() => {
    db.close();
    rmSync(tmpDir, { recursive: true, force: true });
  });

  function getProjectId(): string {
    return `local/${tmpDir.split('/').pop()}`;
  }

  it('generates HANDOFF.md file', () => {
    const projectId = getProjectId();
    const store = new SessionStore(db);
    store.insert(makeSession({ projectId }));

    generateHandoff(db, tmpDir);

    expect(existsSync(join(tmpDir, '.agent-memory', 'HANDOFF.md'))).toBe(true);
  });

  it('includes correct header sections', () => {
    const projectId = getProjectId();
    const store = new SessionStore(db);
    store.insert(makeSession({ projectId }));

    const content = generateHandoff(db, tmpDir);

    expect(content).toContain('# Agent Handoff');
    expect(content).toContain('Auto-generated by');
    expect(content).toContain('**Sessions tracked:** 1');
  });

  it('includes latest session summary', () => {
    const projectId = getProjectId();
    const store = new SessionStore(db);
    store.insert(makeSession({ projectId }));

    const content = generateHandoff(db, tmpDir);

    expect(content).toContain('## Latest Session');
    expect(content).toContain('**Agent:** copilot');
    expect(content).toContain('**Summary:** Implemented authentication module');
  });

  it('includes pending tasks as checklist', () => {
    const projectId = getProjectId();
    const store = new SessionStore(db);
    store.insert(makeSession({ projectId }));

    const content = generateHandoff(db, tmpDir);

    expect(content).toContain('### Pending Tasks');
    expect(content).toContain('- [ ] Add refresh tokens');
    expect(content).toContain('- [ ] Add rate limiting');
  });

  it('includes files modified', () => {
    const projectId = getProjectId();
    const store = new SessionStore(db);
    store.insert(makeSession({ projectId }));

    const content = generateHandoff(db, tmpDir);

    expect(content).toContain('### Files Modified');
    expect(content).toContain('`src/auth.ts`');
    expect(content).toContain('`src/middleware.ts`');
  });

  it('includes key decisions', () => {
    const projectId = getProjectId();
    const store = new SessionStore(db);
    store.insert(makeSession({ projectId }));

    const content = generateHandoff(db, tmpDir);

    expect(content).toContain('### Key Decisions');
    expect(content).toContain('Use bcrypt for hashing');
    expect(content).toContain('JWT expiry 1 hour');
  });

  it('includes session history table for multiple sessions', () => {
    const projectId = getProjectId();
    const store = new SessionStore(db);
    store.insert(makeSession({ projectId, id: 's1', endedAt: '2025-01-14T10:00:00', summary: 'First session' }));
    store.insert(makeSession({ projectId, id: 's2', endedAt: '2025-01-15T10:00:00', summary: 'Second session' }));

    const content = generateHandoff(db, tmpDir);

    expect(content).toContain('## Session History');
    expect(content).toContain('| Agent | When | Summary |');
    expect(content).toContain('First session');
    expect(content).toContain('Second session');
  });

  it('includes knowledge section', () => {
    const projectId = getProjectId();
    const sStore = new SessionStore(db);
    sStore.insert(makeSession({ projectId }));

    const kStore = new KnowledgeStore(db);
    kStore.insert({ projectId, type: 'decision', title: 'Use REST API', content: 'REST over GraphQL for simplicity' });

    const content = generateHandoff(db, tmpDir);

    expect(content).toContain('## Shared Knowledge');
    expect(content).toContain('### Use REST API');
    expect(content).toContain('REST over GraphQL for simplicity');
  });

  it('handles empty sessions', () => {
    const content = generateHandoff(db, tmpDir);

    expect(content).toContain('# Agent Handoff');
    expect(content).toContain('**Sessions tracked:** 0');
    expect(content).not.toContain('## Latest Session');
    expect(content).not.toContain('## Session History');
  });

  it('handles empty knowledge', () => {
    const projectId = getProjectId();
    const store = new SessionStore(db);
    store.insert(makeSession({ projectId }));

    const content = generateHandoff(db, tmpDir);
    expect(content).not.toContain('## Shared Knowledge');
  });

  it('truncates long summaries in history table', () => {
    const projectId = getProjectId();
    const store = new SessionStore(db);
    const longSummary = 'A'.repeat(120);
    store.insert(makeSession({ projectId, id: 's1', endedAt: '2025-01-14T10:00:00', summary: longSummary }));
    store.insert(makeSession({ projectId, id: 's2', endedAt: '2025-01-15T10:00:00', summary: 'Short' }));

    const content = generateHandoff(db, tmpDir);

    expect(content).toContain('A'.repeat(80) + '...');
  });

  it('omits pending tasks section when none exist', () => {
    const projectId = getProjectId();
    const store = new SessionStore(db);
    store.insert(makeSession({ projectId, tasksPending: [] }));

    const content = generateHandoff(db, tmpDir);
    expect(content).not.toContain('### Pending Tasks');
  });

  it('accepts pre-loaded sessions parameter', () => {
    const projectId = getProjectId();
    const store = new SessionStore(db);
    const session = makeSession({ projectId });
    store.insert(session);

    const retrieved = store.getRecent(projectId, 5);
    const content = generateHandoff(db, tmpDir, retrieved);

    expect(content).toContain('Implemented authentication module');
  });
});
