export { getDb, closeDb, createTestDb, getDbPath } from './db/connection.js';
export { SessionStore } from './db/sessions.js';
export { KnowledgeStore } from './db/knowledge.js';
export { VectorStore } from './db/vectors.js';
export { OnnxEmbeddingEngine, EMBEDDING_DIMENSIONS, validateEmbedding } from './embedding/engine.js';
export { chunkText } from './embedding/chunker.js';
export { detectProject, normalizeGitRemote } from './ingest/project-detector.js';
export { CopilotIngester } from './ingest/copilot.js';
export { ClaudeIngester, encodeProjectPath, decodeProjectPath } from './ingest/claude.js';
export { GeminiIngester, getProjectHash } from './ingest/gemini.js';
export { ingestSession } from './ingest/pipeline.js';
export { SessionExtractor } from './summarize/extractor.js';
export type { ExtractedSession } from './summarize/extractor.js';
export { formatHandoffSummary } from './summarize/formatter.js';
export { startServer } from './mcp/server.js';
export { getHandoff, searchMemory, storeKnowledge, getProjectContext } from './mcp/tools.js';
export { loadConfig, saveConfig } from './config.js';
export type { AgentMemoryConfig } from './config.js';
export type * from './types.js';
